### ISSUE TITLE
Source links in Pursuit docs are broken

### ISSUE THREAD

**Issue by mattdiamond** [fehrenbach/purescript-unordered-collections#29]
The `Source` links in the Pursuit docs for this library are broken. For example, the link for `HashMap` leads to:

https://github.com/fehrenbach/purescript-unordered-collections/blob/v2.1.1/src/purescript-unordered-collections/src/Data/HashMap.purs#L69-L69

instead of the correct URL:

https://github.com/fehrenbach/purescript-unordered-collections/blob/v2.1.1/src/Data/HashMap.purs#L69-L69

I'm guessing that all of the Source links have this issue. Not a big deal but would be nice to have those links working.

**Comment by JordanMartinez** [comment]
You could try reuploading the docs for this package.

**Comment by fehrenbach** [comment]
Thanks for the report. That sounds like purescript/pursuit#332. I'll have a look, but probably not before the end of tomorrow.

**Comment by mattdiamond** [comment]
I'll close this ticket since this specific issue has been resolved, but someone may want to create a new ticket elsewhere to examine why the source span isn't (or at least isn't always) relative to the project root, as @hdgarrood expected. Otherwise this issue could re-occur whenever someone publishes a library within a `/src/` directory.

**Comment by hdgarrood** [comment]
The right place for that follow up issue is likely to be the compiler repository, since `purs publish` creates the JSON data which includes this file path in the first place.
