### ISSUE TITLE
"Collision is not defined" when bundling a project using HashMap

### ISSUE THREAD

**Issue by vuolen** [fehrenbach/purescript-unordered-collections#30]
I created a minimal gist reproducing this bug [here](https://gist.github.com/vuolen/c52ec88ee14508e1f62c136f5f44dc81)

When I run `spago bundle-app` and `node index.js` I get the following error:
```
/home/lennu/code/error/index.js:544
  Collision.prototype.lookup = function collisionLookup(Nothing, Just, keyEquals, key, keyHash, shift) {
  ^

ReferenceError: Collision is not defined
    at /home/lennu/code/error/index.js:544:3
    at Object.<anonymous> (/home/lennu/code/error/index.js:743:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

However using `spago run` works normally. I'm using spago v0.20.3 and purs v0.14.5

**Comment by vuolen** [comment]
Okay oddly enough (at least for me), this error does not happen when I do not specify an entry point:
```
[lennu@lennu error]$ purs bundle "output/*/*.js" -m Main --main Main -o index.js
[lennu@lennu error]$ cat index.js | grep "function Collision(keys, values)"
[lennu@lennu error]$ purs bundle "output/*/*.js" -o index.js
[lennu@lennu error]$ cat index.js | grep "function Collision(keys, values)"
  function Collision(keys, values) {
```
For some reason the bundling saves all the function definitions on the prototype, but not the actual constructor.

**Comment by JordanMartinez** [comment]
Just curious, but is this related to https://github.com/purescript/purescript/issues/4181 at all?

**Comment by fehrenbach** [comment]
> Should this issue be moved to the compiler's repo?

Yes, please, if you can. This is definitely a bundler bug.

`Collision` isn't the only function that's "optimized" away. It looks like all the toplevel helpers are gone. I don't know anything about how spago/purs bundle is implemented, but it looks like it fails to preserve references from the right hand sides of the prototype assignments, even though the assignments themselves are preserved. Curious.

In the meantime, I'd definitely consider merging a PR with a workaround if anyone can come up with something reasonable.

`make test-bundle` fails as well (purs 0.14.4, see shell.nix). I hadn't noticed, because CI is defunct :(

**Comment by ozkutuk** [comment]
> Just curious, but is this related to [purescript/purescript#4181](https://github.com/purescript/purescript/issues/4181) at all?

I wonder if this is the case as well. Unfortunately, I couldn't turn my attention into implementing a proper solution as suggested on the proposed PR, but perhaps you could build the compiler with https://github.com/purescript/purescript/pull/4182 and see if it works that way.

**Comment by fehrenbach** [comment]
I just tagged a version of this library for PureScript 0.15, which uses ES modules and gets rid of `purs bundle`: https://github.com/purescript/purescript/issues/4226 Hopefully ES module bundlers are less buggy.
