### ISSUE TITLE
Announcement on discourse?

### ISSUE THREAD

**Issue by paluh** [fehrenbach/purescript-unordered-collections#6]
Would you mind to inform wider public about your cool library and create short post about this lib and its further releases on discourse.purescript.org?
If don't want to spend time on this and you think that this is good idea I can probably help and post some small info there.

**Comment by fehrenbach** [comment]
Sure: https://discourse.purescript.org/t/unordered-collections-1-6-0/435

I don't use discourse, I just created an account for this, so I won't promise that I'll announce future versions, but then again I hope there won't be too many future versions...

**Comment by paluh** [comment]
> Sure: https://discourse.purescript.org/t/unordered-collections-1-6-0/435
>
> I don't use discourse, I just created an account for this, so I won't promise that I'll announce future versions, but then again I hope there won't be too many future versions...

Thanks a lot @fehrenbach !
We are small community and I think it is important to consolidate information and news feed in an open place like discourse (slack is somewhat private and unsearchable etc.).
I hope that in this way we can encourage constructive discussion and maybe build a ecosystem which will more accessible and friendly for newcomers too.
