### ISSUE TITLE
Cannot resolve `Data.Maybe` module

### ISSUE THREAD

**Issue by adnelson** [fehrenbach/purescript-unordered-collections#7]
I just installed version 1.6.0 via bower. Now my build is breaking. The error I'm seeing is:

```
ERROR in ./bower_components/purescript-unordered-collections/src/Data/HashMap.js
Module not found: Error: Can't resolve '../Data.Maybe/index.js' in './bower_components/purescript-unordered-collections/src/Data'
 @ ./bower_components/purescript-unordered-collections/src/Data/HashMap.js 9:17-50
 @ ./bower_components/purescript-unordered-collections/src/Data/HashMap.purs
 @ ./bower_components/purescript-unordered-collections/src/Data/HashSet.purs
 @ ./src/Main.purs
 @ ./src/App.js
 @ multi (webpack)-dev-server/client?http://localhost:4008 (webpack)/hot/dev-server.js ./src/App
ℹ ｢wdm｣: Failed to compile.
```

Looking in that file I see a line

```javascript
var Data_Maybe = require("../Data.Maybe/index.js");
```

But I don't see that file included in the built artifact from bower, or for that matter in the repository. Perhaps there was a regression? Or, is there some step I need to perform?

**Comment by paluh** [comment]
@adnelson Does `bower install purescript-maybe` fixes the issue?

**Comment by adnelson** [comment]
`purescript-maybe` is already installed. For some reason, I can `import Data.HashMap` just fine from the repl (`pulp repl`) but the `purs-loader` is failing to compile, with the above error.

**Comment by adnelson** [comment]
I was able to hack it by changing the argument to `require`. I think it might have something to do with the loader -- rather than running the script from the `output` directory, in which the `../Data.Maybe` relative path is valid, it's running the one from `bower_components`, which doesn't have that structure. I'm pretty new to purescript and its build system, so I'm not sure how to solve this issue, but I have a workaround for now.

**Comment by paluh** [comment]
Could you paste your `bower.json`? Are you able to reproduce this problem on minimal new project?

**Comment by adnelson** [comment]
So here are steps to reproduce my particular case:

```
git clone ssh://git@github.com/ethul/purescript-react-example
cd purescript-react-example
bower install
npm install
```

Confirm that the project works to this point by running `npm run webpack-dev-server` in a new terminal.

Next, edit `src/Main.purs` and add `import Data.HashMap`. The dev server will now complain that `Data.HashMap` isn't found.

Stop the server, run `bower install purescript-unordered-collections`, and start the dev server. Now you'll see the server error with `Can't resolve '../Data.Maybe/index.js`.

**Comment by paluh** [comment]
Yeah, it seems like an loader issue - `pulp build` works fine. To be honest I'm avoiding `purs-loader` because I compile my source inside my vim using a plugin.
@adnelson do you use editor with `purs ide` support?

**Comment by adnelson** [comment]
I've never used `purs ide` -- I'm on emacs, not sure if that's supported. But in any case, I'm new to purescript, so a lot of the build setup in this the example that I started with is just kind of "magic". 

Seeing as this appears to be specific to `purs-loader`, I think I'll close this issue and perhaps open an issue on that project instead. Although, now that I have my workaround, it's easier to put it off... hah

**Comment by adnelson** [comment]
Looks like there's already an issue for this: https://github.com/ethul/purs-loader/issues/111

I'll close this for now and see if there's anything posted on that issue that resolves my problem. Thanks! :)
