### ISSUE TITLE
intersectionWith's type is too specific

### ISSUE THREAD

**Issue by karshan** [fehrenbach/purescript-unordered-collections#9]
intersectionWith shouldn't require the two maps to have the same value type.

see haskell's  [intersectionWith](http://hackage.haskell.org/package/containers-0.6.0.1/docs/Data-Map-Strict.html#v:intersectionWith)

**Comment by fehrenbach** [comment]
You are right. I'm not sure anymore why I went for the restricted type. Maybe to match intersection? (Which could also be generalized (but I'm not keen on doing that).)

Would you like to submit a PR?
